CREATE TABLE IF NOT EXISTS stops (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stop_name VARCHAR(50) NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  post VARCHAR(2) NOT NULL
);

CREATE INDEX IF NOT EXISTS stops_name ON stops(stop_name); 

CREATE TABLE IF NOT EXISTS my_stops (
  id INTEGER  PRIMARY KEY AUTOINCREMENT,
  stop_id INTEGER,
  FOREIGN KEY(stop_id) REFERENCES stops(id)
);

