CREATE TABLE IF NOT EXISTS stops (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stop_name VARCHAR(50) NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  post VARCHAR(2) NOT NULL
);

CREATE INDEX IF NOT EXISTS stops_name ON stops(stop_name); 

CREATE TABLE IF NOT EXISTS my_stops (
  id INTEGER  PRIMARY KEY AUTOINCREMENT,
  stop_id INTEGER,
  FOREIGN KEY(stop_id) REFERENCES stops(id)
);

CREATE TABLE IF NOT EXISTS distances (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  line VARCHAR(4) NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  vehicle_number VARCHAR(10) NOT NULL,
  brigade VARCHAR(4) NOT NULL,
  distance REAL NOT NULL,
  created INTEGER NOT NULL
);

